package exceptionHandlingInFlowimport kotlinx.coroutines.flow.asFlowimport kotlinx.coroutines.flow.catchimport kotlinx.coroutines.flow.collectimport kotlinx.coroutines.flow.onEachimport kotlinx.coroutines.runBlockingfun main() {    runBlocking {        catchExample()    }}suspend fun catchExample(){    (1..3).asFlow()        .onEach{ check(it != 2) }        .catch{ e -> println("Caught Exception $e") }        .collect {            println(it)        }}