package exceptionHandlingInFlowimport kotlinx.coroutines.flow.asFlowimport kotlinx.coroutines.flow.collectimport kotlinx.coroutines.flow.onEachimport kotlinx.coroutines.runBlockingfun main() {    runBlocking {        tryCatch()    }}suspend fun tryCatch(){    try{        (1..3).asFlow()            .onEach{ check(it != 2) }            .collect {                println(it)            }    }    catch(e:Exception){        println("Caught exception")    }}